language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- bandit -r .
- flake8 .
deploy:
  provider: pypi
  user: drewpearce
  password:
    secure: ldGevz6s+FNVp/IFJbHqp6sb949lL48ON4cnh2yJfn+dGbHlLVzuk4SHbtqtOOh+xDZIi+NUhPc7IQg+7KxeaXfMmj2NYNNsOPG+44jaVtj8n3Xeky8Ykq5gtGGqTkFEC8BvRY3tkD5UTDAw23N+KPUi7bNpY2lPA+IukJN0bq2i+/okyrkAaPxbGlmBKqPs/HveKS7JVSfzfQWjRd3GmPqaIMC4TzCf98XPfV2QBu3mUordJ5ZRAxFe9ic50Y8xYN3lIDj/1Ad7HIjZo3q+qdlRM4D1JtxOxuhsEN05MpTA8swF+yCKazP+lYVyNCliGQK6uY7H28IiqsZj17yXwzsh+gZPKdSQNTYoO3fCnR9WdxY8qQlX/yidV6P91KluT+aexah4Ls0UUTPo1xorIfIqGnAi/94MSrRZwCCWsXHf7bqO0W+fz0rCvl6+8scK00IFYMSjNky4LAW7BRNMewawqfKFQOvLK7l9I0q8gvkG1/99iQq2+A8CNSVkCq/bonKETTi6sKhF0QjqZmuT/UCZ1QoWMjtPD/vgA0cbhTkxhVhv0OdKFvVsJOZjyQrc/BYONum0q+nhxec4V4EAetlcy3Rl/kgLs8GvqSCp8lRAJlzOwwNiTozDuqrPepskYIR9a7wkvczasIDr2aKHrliqiWkK85i6vz/nfRBhff8=
  on:
    tags: true
    distributions: sdist bdist_wheel
    branch: master
    repo: drewpearce/legos.apod
