language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- bandit -r .
- flake8 .
deploy:
  provider: pypi
  user: drewpearce
  password:
    secure: VajsI8DBqK6FUuKdrMa04Nfdq3tzgZl5aKy6CDSt2vkQJXU3F1wCI2dAPb1TItdSJLZN9MWUaT3/NHUiocCXi5RhlmdUKNntEHAedKOY1wfA3LeGJhuNLaD6004D3Z/oAGcjhXVJ0faILQJrm+XxCYIibmpwlWcV6AjpdHCgRvllPrhoWhJU4k2ZBa61Imp5gOJKk1g5dRthgIyqG6ebFEL+gA6sVATB0IluHKaMJJFD/+GKJu3t8h7uvEBTneqLw9eBqvEBVzJg6yIFwqhmo/+naQP+R1TUklmNrxUopZfl27ny83vemJSjUALXij1CEmACwfGrhNuDnq0G4VBErOiWDXjFU1ULLRFabnH+q0rC9lyhMyyWfwdtME6uRphGu0Jz9YQfQf4T3Cs63Ti5OgQZJ7sicRPcwHQr8v2vIgX8+rDLzsDxdKvKVQUUd9OIXVMitL8RX7tUSX7HsaEDanXCqYsXyM7h6Qik5B3qdXGgt/ya6NO9iNJWJitUT3bOj4R6fekAdkNrFP4w/8owEdsUtsr7vGf0NYoPknVnRTQAzydGW4nXGZyNEhaocfK3rvdcOmjytAPy2ynDcp6f++A4M0ywjxv3EhvK6A1X+uO32ZapTdNXP/N9Algk7gt0V8oAi3OQVvl+oIJMSUWONlx/fU/JJ37yFENUg2RUuVE=
  on:
    tags: true
    distributions: sdist bdist_wheel
    branch: master
    repo: drewpearce/legos.apod
